import discord
from discord.ext import commands
import Paginator

@commands.command()
async def agentes(ctx):

    Embed1 = discord.Embed(title="Brimstone", description="Agente número 01", colour = discord.Colour.brand_red())
    Embed1.set_image(url="https://www.esports.net/wp-content/uploads/2022/08/Valorant-Brimstone-Guide.png")
    Embed1.add_field(name = "Origem", value = "Estados Unidos", inline = True)
    Embed1.add_field(name = "Role", value = "Controlador", inline = True)
    Embed1.add_field(name = "Habilidades Básicas", value = "Incendiário e Sinalizador Estimulante", inline = True)
    Embed1.add_field(name = "Habilidade de Assinatura", value = "Fumaça Celeste", inline = True)
    Embed1.add_field(name = "Ultimate", value = "Ataque Orbital", inline = True)
    Embed1.add_field(name = "Pontos de Ultimate", value = "7 pontos", inline = True)

    Embed2 = discord.Embed(title="Viper", description="Agente número 02", colour = discord.Colour.brand_red())
    Embed2.set_image(url="https://static.wikia.nocookie.net/valorant/images/5/5f/Viper_icon.png/revision/latest?cb=20201128234408")
    Embed2.add_field(name = "Origem", value = "Estados Unidos", inline = True)
    Embed2.add_field(name = "Role", value = "Controlador", inline = True)
    Embed2.add_field(name = "Habilidades Básicas", value = "Nuvem Venenosa e Veneno de Cobra", inline = True)
    Embed2.add_field(name = "Habilidade de Assinatura", value = "Cortina Tóxica", inline = True)
    Embed2.add_field(name = "Ultimate", value = "Poço Peçonhento", inline = True)
    Embed2.add_field(name = "Pontos de Ultimate", value = "8 pontos", inline = True)

    Embed3 = discord.Embed(title="Omen", description="Agente número 03", colour = discord.Colour.brand_red())
    Embed3.set_image(url="https://static.wikia.nocookie.net/valorant/images/b/b0/Omen_icon.png/revision/latest?cb=20201128234318")
    Embed3.add_field(name = "Origem", value = "Terra", inline = True)
    Embed3.add_field(name = "Role", value = "Controlador", inline = True)
    Embed3.add_field(name = "Habilidades Básicas", value = "Paranóia e Passos Tenebrosos", inline = True)
    Embed3.add_field(name = "Habilidade de Assinatura", value = "Manto Sombrio", inline = True)
    Embed3.add_field(name = "Ultimate", value = "Salto das Sombras", inline = True)
    Embed3.add_field(name = "Pontos de Ultimate", value = "7 pontos", inline = True)

    Embed4 = discord.Embed(title="Killjoy", description="Agente número 04", colour = discord.Colour.brand_red())
    Embed4.set_image(url="https://valorantinfo.com/images/br/killjoy_valorant_icon_3073.webp")
    Embed4.add_field(name = "Origem", value = "Alemanha", inline = True)
    Embed4.add_field(name = "Role", value = "Sentinela", inline = True)
    Embed4.add_field(name = "Habilidades Básicas", value = "Robô de Alarme e Nanoenxame", inline = True)
    Embed4.add_field(name = "Habilidade de Assinatura", value = "Torreta", inline = True)
    Embed4.add_field(name = "Ultimate", value = "Confinamento", inline = True)
    Embed4.add_field(name = "Pontos de Ultimate", value = "8 pontos", inline = True)
    
    Embed5 = discord.Embed(title="Cypher", description="Agente número 05", colour = discord.Colour.brand_red())
    Embed5.set_image(url="https://static.wikia.nocookie.net/valorant/images/8/88/Cypher_icon.png/revision/latest?cb=20201128234211")
    Embed5.add_field(name = "Origem", value = "Marrocos", inline = True)
    Embed5.add_field(name = "Role", value = "Sentinela", inline = True)
    Embed5.add_field(name = "Habilidades Básicas", value = "Jaula Cibernética e Fio-Amadilha", inline = True)
    Embed5.add_field(name = "Habilidade de Assinatura", value = "Câmera de Vigilância", inline = True)
    Embed5.add_field(name = "Ultimate", value = "Assalto Neural", inline = True)
    Embed5.add_field(name = "Pontos de Ultimate", value = "6 pontos", inline = True)

    Embed6 = discord.Embed(title="Sova", description="Agente número 06", colour = discord.Colour.brand_red())
    Embed6.set_image(url="https://valorantinfo.com/images/br/sova_valorant_icon_3072.webp")
    Embed6.add_field(name = "Origem", value = "Rússia", inline = True)
    Embed6.add_field(name = "Role", value = "Iniciador", inline = True)
    Embed6.add_field(name = "Habilidades Básicas", value = "Flecha de Choque e Drone Coruja", inline = True)
    Embed6.add_field(name = "Habilidade de Assinatura", value = "Flecha Rastreadora", inline = True)
    Embed6.add_field(name = "Ultimate", value = "Fúria do Caçador", inline = True)
    Embed6.add_field(name = "Pontos de Ultimate", value = "8 pontos", inline = True)

    Embed7 = discord.Embed(title="Sage", description="Agente número 07", colour = discord.Colour.brand_red())
    Embed7.set_image(url="https://www.esports.net/wp-content/uploads/2022/08/Sage-Valorant.png")
    Embed7.add_field(name = "Origem", value = "China", inline = True)
    Embed7.add_field(name = "Role", value = "Sentinela", inline = True)
    Embed7.add_field(name = "Habilidades Básicas", value = "Orbe de lentidão e Orbe de Barreira", inline = True)
    Embed7.add_field(name = "Habilidade de Assinatura", value = "Orbe Curativo", inline = True)
    Embed7.add_field(name = "Ultimate", value = "Ressurreição", inline = True)
    Embed7.add_field(name = "Pontos de Ultimate", value = "8 pontos", inline = True)

    Embed8 = discord.Embed(title="Phoenix", description="Agente número 09", colour = discord.Colour.brand_red())
    Embed8.set_image(url="https://cdn.skins.co/VKVMQmMF9hYHu64KF_AQRV16EoLESXqdBk-GwB3-0Bs/rs:fit:260:260:0/g:no/aHR0cHM6Ly9za2lucy5jby9zdG9yYWdlL2ltYWdlcy83YTA5Zjk1ZTk0YjA0ZjZkYjBhOGFiYzU0MzFjYjMzYS5wbmc.webp")
    Embed8.add_field(name = "Origem", value = "Reino Unido", inline = True)
    Embed8.add_field(name = "Role", value = "Duelista", inline = True)
    Embed8.add_field(name = "Habilidades Básicas", value = "Bola Curva e Labareda", inline = True)
    Embed8.add_field(name = "Habilidade de Assinatura", value = "Mãos quentes", inline = True)
    Embed8.add_field(name = "Ultimate", value = "Renascimento", inline = True)
    Embed8.add_field(name = "Pontos de Ultimate", value = "6 pontos", inline = True)

    Embed9 = discord.Embed(title="Jett", description="Agente número 10", colour = discord.Colour.brand_red())
    Embed9.set_image(url="https://valorantinfo.com/images/br/jett_valorant_icon_3084.webp")
    Embed9.add_field(name = "Origem", value = "Coréia do Sul", inline = True)
    Embed9.add_field(name = "Role", value = "Duelista", inline = True)
    Embed9.add_field(name = "Habilidades Básicas", value = "Corrente Ascendente e Erupção das Brumas", inline = True)
    Embed9.add_field(name = "Habilidade de Assinatura", value = "Brisa de Impulso", inline = True)
    Embed9.add_field(name = "Ultimate", value = "Tormenta de Aço", inline = True)
    Embed9.add_field(name = "Pontos de Ultimate", value = "7 pontos", inline = True)

    Embed10 = discord.Embed(title="Reyna", description="Agente número 11", colour = discord.Colour.brand_red())
    Embed10.set_image(url="https://static.wikia.nocookie.net/valorant/images/b/b0/Reyna_icon.png/revision/latest?cb=20200607180311")
    Embed10.add_field(name = "Origem", value = "México", inline = True)
    Embed10.add_field(name = "Role", value = "Duelista", inline = True)
    Embed10.add_field(name = "Habilidades Básicas", value = "Devorar e Olhar Voraz", inline = True)
    Embed10.add_field(name = "Habilidade de Assinatura", value = "Dispensar", inline = True)
    Embed10.add_field(name = "Ultimate", value = "Imperatriz", inline = True)
    Embed10.add_field(name = "Pontos de Ultimate", value = "6 pontos", inline = True)

    Embed11 = discord.Embed(title="Raze", description="Agente número 12", colour = discord.Colour.brand_red())
    Embed11.set_image(url="https://static.wikia.nocookie.net/valorant/images/9/9c/Raze_icon.png/revision/latest?cb=20201128234400")
    Embed11.add_field(name = "Origem", value = "Brasil", inline = True)
    Embed11.add_field(name = "Role", value = "Duelista", inline = True)
    Embed11.add_field(name = "Habilidades Básicas", value = "Carga de Explosivos e Bumba", inline = True)
    Embed11.add_field(name = "Habilidade de Assinatura", value = "Cartuchos de Tinta", inline = True)
    Embed11.add_field(name = "Ultimate", value = "Estraga-Prazeres", inline = True)
    Embed11.add_field(name = "Pontos de Ultimate", value = "8 pontos", inline = True)

    Embed12 = discord.Embed(title="Breach", description="Agente número 13", colour = discord.Colour.brand_red())
    Embed12.set_image(url="https://static.wikia.nocookie.net/valorant/images/5/53/Breach_icon.png/revision/latest?cb=20201128234328")
    Embed12.add_field(name = "Origem", value = "Suécia", inline = True)
    Embed12.add_field(name = "Role", value = "Iniciador", inline = True)
    Embed12.add_field(name = "Habilidades Básicas", value = "Estopim e Pós-Choque", inline = True)
    Embed12.add_field(name = "Habilidade de Assinatura", value = "Falha Tectônica", inline = True)
    Embed12.add_field(name = "Ultimate", value = "Onda Trovejante", inline = True)
    Embed12.add_field(name = "Pontos de Ultimate", value = "8 pontos", inline = True)

    Embed13 = discord.Embed(title="Skye", description="Agente número 14", colour = discord.Colour.brand_red())
    Embed13.set_image(url="https://static.wikia.nocookie.net/valorant/images/3/33/Skye_icon.png/revision/latest?cb=20201128234628")
    Embed13.add_field(name = "Origem", value = "Austrália", inline = True)
    Embed13.add_field(name = "Role", value = "Iniciador", inline = True)
    Embed13.add_field(name = "Habilidades Básicas", value = "Predador Explosivo e Reflorescer", inline = True)
    Embed13.add_field(name = "Habilidade de Assinatura", value = "Luz Desbravadora", inline = True)
    Embed13.add_field(name = "Ultimate", value = "Rastreadores", inline = True)
    Embed13.add_field(name = "Pontos de Ultimate", value = "7 pontos", inline = True)

    Embed14 = discord.Embed(title="Yoru", description="Agente número 15", colour = discord.Colour.brand_red())
    Embed14.set_image(url="https://valorantinfo.com/images/br/yoru_valorant_icon_3080.webp")
    Embed14.add_field(name = "Origem", value = "Japão", inline = True)
    Embed14.add_field(name = "Role", value = "Duelista", inline = True)
    Embed14.add_field(name = "Habilidades Básicas", value = "Ponto Cego e Distração", inline = True)
    Embed14.add_field(name = "Habilidade de Assinatura", value = "Passagem Dimensional", inline = True)
    Embed14.add_field(name = "Ultimate", value = "Espionagem Dimensional", inline = True)
    Embed14.add_field(name = "Pontos de Ultimate", value = "7 pontos", inline = True)

    Embed15 = discord.Embed(title="Astra", description="Agente número 16", colour = discord.Colour.brand_red())
    Embed15.set_image(url="https://static.wikia.nocookie.net/valorant/images/0/08/Astra_icon.png/revision/latest?cb=20210302164234")
    Embed15.add_field(name = "Origem", value = "Gana", inline = True)
    Embed15.add_field(name = "Role", value = "Controlador", inline = True)
    Embed15.add_field(name = "Habilidades Básicas", value = "Pulso Nova e Poço Gravitacional", inline = True)
    Embed15.add_field(name = "Habilidade de Assinatura", value = "Nebulosa", inline = True)
    Embed15.add_field(name = "Ultimate", value = "Divisa Cósmica", inline = True)
    Embed15.add_field(name = "Pontos de Ultimate", value = "7 pontos", inline = True)

    Embed16 = discord.Embed(title="KAY/O", description="Agente número 17", colour = discord.Colour.brand_red())
    Embed16.set_image(url="https://static.wikia.nocookie.net/valorant/images/f/f0/KAYO_icon.png/revision/latest?cb=20210622225019")
    Embed16.add_field(name = "Origem", value = "Realidade Alternativa da Terra", inline = True)
    Embed16.add_field(name = "Role", value = "Iniciador", inline = True)
    Embed16.add_field(name = "Habilidades Básicas", value = "Granada/Clarão e Frag/mento", inline = True)
    Embed16.add_field(name = "Habilidade de Assinatura", value = "Ponto/zero", inline = True)
    Embed16.add_field(name = "Ultimate", value = "Anular/CMD", inline = True)
    Embed16.add_field(name = "Pontos de Ultimate", value = "8 pontos", inline = True)

    Embed17 = discord.Embed(title="Chamber", description="Agente número 18", colour = discord.Colour.brand_red())
    Embed17.set_image(url="https://static.wikia.nocookie.net/valorant/images/0/09/Chamber_icon.png/revision/latest?cb=20211113013323")
    Embed17.add_field(name = "Origem", value = "França", inline = True)
    Embed17.add_field(name = "Role", value = "Sentinela", inline = True)
    Embed17.add_field(name = "Habilidades Básicas", value = "Caçador de Cabeças e Marca Registrada", inline = True)
    Embed17.add_field(name = "Habilidade de Assinatura", value = "Rendezvous", inline = True)
    Embed17.add_field(name = "Ultimate", value = "Tour de Force", inline = True)
    Embed17.add_field(name = "Pontos de Ultimate", value = "8 pontos", inline = True)
    
    Embed18 = discord.Embed(title="Neon", description="Agente número 19", colour = discord.Colour.brand_red())
    Embed18.set_image(url="https://valorantinfo.com/images/br/neon_valorant_icon_3079.webp")
    Embed18.add_field(name = "Origem", value = "Filipinas", inline = True)
    Embed18.add_field(name = "Role", value = "Duelista", inline = True)
    Embed18.add_field(name = "Habilidades Básicas", value = "Ricochete Elétrico e Via Expressa", inline = True)
    Embed18.add_field(name = "Habilidade de Assinatura", value = "Equipamento Voltaico", inline = True)
    Embed18.add_field(name = "Ultimate", value = "Sobrecarga", inline = True)
    Embed18.add_field(name = "Pontos de Ultimate", value = "7 pontos", inline = True)

    Embed19 = discord.Embed(title="Fade", description="Agente número 20", colour = discord.Colour.brand_red())
    Embed19.set_image(url="https://static.wikia.nocookie.net/valorant/images/a/a6/Fade_icon.png/revision/latest?cb=20220525095157")
    Embed19.add_field(name = "Origem", value = "Turquia", inline = True)
    Embed19.add_field(name = "Role", value = "Iniciador", inline = True)
    Embed19.add_field(name = "Habilidades Básicas", value = "Clausura e Espreitador", inline = True)
    Embed19.add_field(name = "Habilidade de Assinatura", value = "Assombrar", inline = True)
    Embed19.add_field(name = "Ultimate", value = "Véu da Noite", inline = True)
    Embed19.add_field(name = "Pontos de Ultimate", value = "8 pontos", inline = True)

    Embed20 = discord.Embed(title="Harbor", description="Agente número 21", colour = discord.Colour.brand_red())
    Embed20.set_image(url="https://static.wikia.nocookie.net/valorant/images/f/f3/Harbor_icon.png/revision/latest?cb=20221018133629")
    Embed20.add_field(name = "Origem", value = "India", inline = True)
    Embed20.add_field(name = "Role", value = "Controlador", inline = True)
    Embed20.add_field(name = "Habilidades Básicas", value = "Maré Alta e Cascata", inline = True)
    Embed20.add_field(name = "Habilidade de Assinatura", value = "Enseada", inline = True)
    Embed20.add_field(name = "Ultimate", value = "Acerto de Contas", inline = True)
    Embed20.add_field(name = "Pontos de Ultimate", value = "7 pontos", inline = True)

    embeds = [Embed1, Embed2, Embed3, Embed4, Embed5, Embed6, Embed7, Embed8, Embed9, Embed10, Embed11, Embed12, Embed13, Embed14, Embed15, Embed16, Embed17, Embed18, Embed19, Embed20]

    await Paginator.Simple().start(ctx, pages=embeds)

async def setup(bot):
        bot.add_command(agentes)